version: "3"

services:
#  db:
#    image: postgres:12
#    environment:
#      - POSTGRES_DB=express-ts
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: .
      dockerfile: compose/Dockerfile-dev
    volumes:
      - ./src:/app/src
    ports:
      - "3200:3200"
#    depends_on:
#      - db
    environment:
      - POSTGRES_DB=startnode1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=host.docker.internal